<a href="https://colab.research.google.com/github/aryan00719/ML-Lab/blob/main/ML_Lab_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import libraries
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense
from tensorflow.keras.utils import to_categorical

In [2]:
# Column names
columns = [
    "sepal_length",
    "sepal_width",
    "petal_length",
    "petal_width",
    "species"
]

In [4]:
# Load dataset
from sklearn.datasets import load_iris

# Load the IRIS Dataset from sklearn
iris = load_iris()
data = pd.DataFrame(data=iris.data, columns=iris.feature_names)
data['species'] = iris.target

# Map numerical species to their names
species_map = {i: name for i, name in enumerate(iris.target_names)}
data['species'] = data['species'].map(species_map)

In [5]:
# Remove empty rows
data = data.dropna()

In [6]:
# Features and target
X = data.iloc[:, 0:4].values
y = data.iloc[:, 4].values

In [7]:
# Encode species labels
encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [8]:
# Convert to categorical (for CNN output layer)
y = to_categorical(y)

In [9]:
# Feature scaling
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [10]:
# Reshape for CNN (samples, steps, channels)
X = X.reshape(X.shape[0], X.shape[1], 1)

In [11]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [12]:
# CNN Model
model = Sequential()

model.add(Conv1D(filters=32, kernel_size=2, activation='relu', input_shape=(4,1)))
model.add(MaxPooling1D(pool_size=2))

model.add(Flatten())

model.add(Dense(16, activation='relu'))
model.add(Dense(3, activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [13]:
# Compile model
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [14]:
# Train model
model.fit(X_train, y_train, epochs=50, batch_size=5, verbose=1)

Epoch 1/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.3167 - loss: 1.1814
Epoch 2/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2917 - loss: 1.1155 
Epoch 3/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4167 - loss: 1.0726 
Epoch 4/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5250 - loss: 1.0464 
Epoch 5/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5917 - loss: 1.0184 
Epoch 6/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6417 - loss: 0.9906 
Epoch 7/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6333 - loss: 0.9669 
Epoch 8/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6250 - loss: 0.9403 
Epoch 9/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6500 - loss: 0.9126 
Epoch 10/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6667 - loss: 0.8853 
Epoch 11/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6917 - loss: 0.8553 
Epoch 12/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0

In [16]:
# Prediction
y_pred = model.predict(X_test)

y_pred_classes = np.argmax(y_pred, axis=1)
y_test_classes = np.argmax(y_test, axis=1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step


In [17]:
# Evaluation
print("Accuracy:", accuracy_score(y_test_classes, y_pred_classes))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test_classes, y_pred_classes))

print("\nClassification Report:")
print(classification_report(y_test_classes, y_pred_classes))

Accuracy: 0.8666666666666667

Confusion Matrix:
[[10  0  0]
 [ 1  8  0]
 [ 2  1  8]]

Classification Report:
              precision    recall  f1-score   support

           0       0.77      1.00      0.87        10
           1       0.89      0.89      0.89         9
           2       1.00      0.73      0.84        11

    accuracy                           0.87        30
   macro avg       0.89      0.87      0.87        30
weighted avg       0.89      0.87      0.87        30

